### ISSUE TITLE
Test Spawn on Ubuntu 20.04

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-buildings#2484]
This issue is to test Spawn on Ubuntu 20.04 to see if it works and if not, whether there is an easy correction or new Spawn binaries would be needed which would not be addressed before the release.

**Comment by mwetter** [comment]
Commit 97600b1e0351af229575a49fa60b5ae558763624 (from the master branch) works with Ubuntu 20.04.
```
simulateModel("Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.Unconditioned", stopTime=432000, tolerance=1e-06, resultFile="Unconditioned");
 = true
```


The test was done with the dassl solver because Dymola on Ubuntu 20.04 needs special setup for CVode and Radau due to changes in glibc (related to `undefined reference to `__pow_finite'`).
